name: Pytest Check

on:
  push:
    paths:
      - 'src'
  pull_request:
    paths:
      - 'src'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3

      - name: Installs dependencies
        run: |
          rye sync
      - name: Run Pytest
        run: |
          rye run test
